In [45]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np
from sklearn.datasets import load_digits

digits = load_digits()

In [46]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(digits.data, digits.target, test_size=0.3)

In [47]:
lr = LogisticRegression(max_iter=10000)
lr.fit(x_train, y_train)
lr.score(x_test, y_test)

0.9722222222222222

In [48]:
svm = SVC()
svm.fit(x_train, y_train)
svm.score(x_test, y_test)

0.9888888888888889

In [73]:
rf = RandomForestClassifier(n_estimators=40)
rf.fit(x_train, y_train)
rf.score(x_test, y_test)

0.9332220367278798

In [74]:
from sklearn.model_selection import KFold
kf = KFold(n_splits = 3)
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [75]:
for train_index, test_index in kf.split([1,2,3,4,5,6,7,8,9]):
    print(train_index, test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [76]:
def get_score(model,x_train,x_test,y_train,y_test):
    model.fit(x_train, y_train)
    return model.score(x_test,y_test)

In [77]:
from sklearn.model_selection import StratifiedKFold
folds = StratifiedKFold(n_splits=3)

In [78]:
scores_l = []
scores_svm = []
scores_rf = []

for train_index, test_index in kf.split(digits.data):
    x_train, x_test, y_train, y_test = digits.data[train_index], digits.data[test_index], \
                                        digits.target[train_index], digits.target[test_index]
    scores_l.append(get_score(LogisticRegression(max_iter=10000), x_train, x_test, y_train, y_test))
    scores_svm.append(get_score(SVC(), x_train, x_test, y_train, y_test))
    scores_rf.append(get_score(RandomForestClassifier(), x_train, x_test, y_train, y_test))

In [79]:
scores_l

[0.9248747913188647, 0.9432387312186978, 0.9148580968280468]

In [80]:
scores_svm

[0.9666110183639399, 0.9816360601001669, 0.9549248747913188]

In [82]:
scores_rf

[0.9382303839732888, 0.9549248747913188, 0.9348914858096828]

In [83]:
from sklearn.model_selection import cross_val_score

In [86]:
cross_val_score(LogisticRegression(max_iter=10000), digits.data,digits.target)

array([0.92222222, 0.87222222, 0.94150418, 0.94150418, 0.89693593])

In [88]:
cross_val_score(SVC(max_iter=10000), digits.data,digits.target)

array([0.96111111, 0.94444444, 0.98328691, 0.98885794, 0.93871866])

In [90]:
cross_val_score(RandomForestClassifier(), digits.data,digits.target)

array([0.93055556, 0.91111111, 0.96100279, 0.97214485, 0.91922006])